### PR TITLE
Update PHPCS and rules to be compatible with PHP 8

### PR DESCRIPTION
**Pull request by jom**
Based on branch in https://github.com/Automattic/WP-Job-Manager/pull/2427

### Changes proposed in this Pull Request

* Update PHPCS so that it works on PHP 8.

### Testing instructions

* Run `composer install`
* Ensure `phpcs` runs on PHP 8 and PHP 7.4.

### CODE REVIEW

**Review by interlineae — APPROVED** [review]
I had to run `composer update` before `composer install`, but after doing that, `vendor/bin/phpcs` runs on both PHP 7.4 and 8.1 on macOS.

It looks like the automated tests are failing on that same `composer update` step.

**Comment by jom** [comment]
@anaemnesis should be fixed by a9d6a81369b0e6bbd4ff462cc88986be443533f1

**Comment by interlineae** [comment]
@jom on `composer install` I hit this now:

```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - doctrine/instantiator is locked to version 2.0.0 and an update of this package was not requested.
    - doctrine/instantiator 2.0.0 requires php ^8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 2
    - doctrine/instantiator 2.0.0 requires php ^8.1 -> your php version (7.4.33) does not satisfy that requirement.
    - phpunit/phpunit 9.6.8 requires doctrine/instantiator ^1.3.1 || ^2 -> satisfiable by doctrine/instantiator[2.0.0].
    - phpunit/phpunit is locked to version 9.6.8 and an update of this package was not requested.
```

**Comment by jom** [comment]
@anaemnesis Fixed the PHP 7.4 install issue in https://github.com/Automattic/WP-Job-Manager/pull/2428/commits/63e7c3dad60c67db32ac5ff660973e6b254df0ae. That changed some rulesets and opened up the issues ignored in https://github.com/Automattic/WP-Job-Manager/pull/2428/commits/554a04c89cdfb4684c2efd9a40a371bf8cab62cb

**Comment by interlineae** [comment]
@jom Works well

**Pull request merged**
