### PR TITLE
Release 1.32.0

### PR DESCRIPTION
**Pull request by jom**
Release for 1.32.0

[Closed Issues](https://github.com/Automattic/WP-Job-Manager/issues?q=is%3Aissue+milestone%3A1.32.0+is%3Aclosed) | [PRs](https://github.com/Automattic/WP-Job-Manager/pulls?q=is%3Apr+milestone%3A1.32.0+is%3Aclosed) | [Diff](https://github.com/Automattic/WP-Job-Manager/compare/1.31.3...release/1.32.0)

### Timeline
- Target Release: ~2019-01-15~ 2019-01-23
- Beta 2: 2019-01-18 [Beta 2 Release](https://github.com/Automattic/WP-Job-Manager/releases/tag/1.32.0-beta2) | [Download](https://github.com/Automattic/WP-Job-Manager/releases/download/1.32.0-beta2/wp-job-manager-1.32.0-beta2.zip)
- Beta 1: 2018-12-17 [Beta 1 Release](https://github.com/Automattic/WP-Job-Manager/releases/tag/1.32.0-beta1) | [Download](https://github.com/Automattic/WP-Job-Manager/releases/download/1.32.0-beta1/wp-job-manager-1.32.0-beta1.zip)

### Things to Test
- Theme compatibility on `[jobs]` shortcode with category select fields. Try with multiple category select option enabled and disabled.
- Theme compatibility with frontend styles. As deprecated in an earlier release, frontend styles must be told when to be enqueued using `job_manager_enqueue_frontend_style` filter. See [this code](https://github.com/Automattic/wp-job-manager/blob/c0938ad4a3224f793d6663d23b7a430906babb84/wp-job-manager.php#L448-L476).
- Permalink settings persist when moving an existing instance to 1.32.0.
- Author selection works when editing a job listing in WP admin.
- See changelog for additional things to look at.

Comment on this PR with any issues that are found.

### Changelog:
```
= 1.32.0 =
* Enhancement: Switched from Chosen to Select2 for enhanced dropdown handling and better mobile support. May require theme update.
* Enhancement: Draft and unsubmitted job listings now appear in `[job_dashboard]`, allowing users to complete their submission.
* Enhancement: Filled and expired positions are now hidden from WordPress search. (@felipeelia)
* Enhancement: Adds additional support for the new block editor. Restricted to classic block for compatibility with frontend editor.
* Enhancement: Job types can be preselected in `[jobs]` shortcode with `?search_job_type=term-slug`. (@felipeelia)
* Enhancement: Author selection in WP admin now uses a searchable dropdown.
* Enhancement: Setup wizard is accessed with a flash message instead of an automatic redirect upon activation.
* Enhancement: When using supported themes, job listing archive slug can be changed in Permalink settings.
* Fix: Company tagline alignment issue with company name. (@0xDELS)
* Fix: "Load Previous Listings" link unnecessarily shows up on `[jobs]` shortcode. (@tonytettinger)
* Fix: Category selector fixed in the job listings page in WP Admin. (@AmandaJBell)
* Fix: Issue with quote encoding on Apply for Job email link.
* Fix: Link `target` attributes have been removed in templates.
* Dev: Allow for job submission flow to be interrupted using `before` argument on form steps.
* Dev: HTML allowed in custom company field labels. (@tripflex)
* Dev: Job feed slug name can be customized with the `job_manager_job_feed_name` filter.
* Deprecated: Unreleased REST API implementation using `WPJM_REST_API_ENABLED` was replaced with standard WP REST API.
```

### CODE REVIEW

**Comment by vetpetjobs** [comment]
Enhancement to new Draft Job Ad feature (sorry if this is the wrong place to post this)

Steps to Reproduce

1 - Given the proposed new ability to retain draft Job Ads
2 - Create a special "View Only" link so that Managers/Clients can View an Unpublished Draft Job Ad (not logged in to WP)
3 - Allow copy and paste link into external email client or simple "Send this link to"
4 - No need for any complex approval process, merely to allow third parties (not logged in to WP) to preview a Job Ad prior to publishing
5 - Non indexable by Search Engines

What I Expected
N/a
What Happened Instead
N/a
WordPress / WP Job Manager Version
5.01+/WP 1.32.0-beta1
Browser / OS Version
All
Screenshot / Video

N/a - haven't seen new Draft Job Ad styling
Context / Source

We are multi-users of WP Job Manager

**Comment by alexsanford** [comment]
The width of the Category input on the Jobs page does not appear to resizing with the parent container.

GIF: http://cld.wthms.co/SiNXRa

This happens for both the multiselect and single-select versions of the input. It does not appear to be theme-dependent (I'm seeing it happen on Twenty Nineteen, Twenty Seventeen, and Divi).

**Comment by alexsanford** [comment]
On Jobify, upgrading to 1.32.0 causes the Category select box to render as a normal HTML multiselect. It does not use Chosen OR Select2.

http://cld.wthms.co/CKthrh

**Comment by alexsanford** [comment]
On Listify, the "Post a Job" page is showing two renders of the Category selection dropdown, one with Select2 and one with Chosen.

It's worth noting that the "Submit Resume" page does not have the same problem. It uses only Select2 for the dropdown. I'm using the current `master` branch of Resumes, which is the 1.17.1 beta.

http://cld.wthms.co/SjyMRW

**Comment by alexsanford** [comment]
When posting a job on Listable, I'm seeing a horizontal scrollbar on the Select2 UI for the Category select.

http://cld.wthms.co/Pj40Kc

I'm also seeing this on the Category select on the Resumes page and the Submit Resume page.

**Comment by alexsanford** [comment]
On the Specialty theme, upgrading to 1.32.0 causes the Category select box to render as a normal HTML multiselect. It does not use Chosen OR Select2.

http://cld.wthms.co/BTv2rU

Note that this happens on the `/jobs` page, which is the archive page. For a normal page using the shortcode, I do not see this behaviour.

**Comment by anastis** [comment]
Hi, co-author of Specialty, colleague of @tsiger here.
Specialty will probably need an update no matter what, as it utilizes Chosen in a custom page template and both the `job_listing_category` and `job_listing_type` taxonomy archives, in addition to the post type archive and the shortcode pages mentioned above. 

Until we change it to work with select2, this should maintain compatibility with the new version:
`
	add_filter( 'job_manager_chosen_enabled', 'ci_theme_wpjm_maybe_enqueue_chosen' );
	function ci_theme_wpjm_maybe_enqueue_chosen() {
		if ( is_post_type_archive( 'job_listing' ) ||
		     is_tax( array( 'job_listing_category', 'job_listing_type' ) ) ||
		     is_page_template( array( 'template-listing-jobs.php' ) )
		) {
			return true;
		}

		return false;
	}
`

However, it doesn't quite work. Not sure if it's a bug or a design decision, but this bit has been removed, making the (theme's) initialization of chosen, fail:
`
wp_localize_script(
	'chosen', 'job_manager_chosen_multiselect_args',
	apply_filters(
		'job_manager_chosen_multiselect_args', array(
			'search_contains' => true,
		)
	)
);
`

@jom happy to share the latest version of the theme with you. Let me know how/where.

**Comment by jom** [comment]
@anastis The localization was taken out because we don't use it in core, but I've added it back in on #1659 (during the deprecation phase) if others are referencing that.

I've also set it to load `select2` (not `chosen`) on taxonomy and archive pages in #1659. This won't fix the issue on Specialty for the drop down using a standard drop down.

**Comment by jom** [comment]
I'm pushing the final release until next week (2019-01-22). Beta 2 should be out tomorrow (2019-01-15).

**Comment by jom** [comment]
[Beta 2 released](https://github.com/Automattic/WP-Job-Manager/releases/tag/1.32.0-beta2). Final release scheduled for 2019-01-23 (next Wednesday).

**Pull request merged**
