### PR TITLE
Fix bug in user editing permission function

### PR DESCRIPTION
**Pull request by jamesjonesphoenix**
I'm experiencing a bug where when a user gets 'invalid listing' when they got to edit one of their listings. The problem is that $job->post_author is a string and the if statement is strict. One line code change fixes it.

### CODE REVIEW

**Comment by tripflex** [comment]
You may need to rebase your fork as there are conflicts preventing merge (if this PR is approved), I think it may be the new user notification merge you have in that branch

**Comment by jamesjonesphoenix** [comment]
Did that do the trick? I'm still a bit new to the ol' github

**Comment by spencerfinnell** [comment]
Pretty sure this was fixed with https://github.com/Automattic/WP-Job-Manager/commit/264c375aa440b46144dd3826943a65f919ae1fca already.

**Comment by mikejolley** [comment]
'twas

**Pull request closed without merging**
