### PR TITLE
Hide Apply for Job button for employer

### LINKED ISSUE #1674: Hide Apply for Job button for employer
#### Steps to Reproduce
1. I created a USER new account in the ROLE of EMPLOYER
2. I added a new job listing with the new account
3. I approved the job listing in my ADMIN account
4. I clicked on MANAGE JOBS in my site which points to this URL

http://www.vedarecruitment.co.uk/job/luton-school-london-16-teacher/

5. I don't know why the APPLY FOR JOB button shows on this page - I am the EMPLOYER - the person who created the job listing - why would I want to apply for the job.

#### What I Expected

I expected the APPLY FOR JOB BUTTON not to be on this page
http://www.vedarecruitment.co.uk/job/luton-school-london-16-teacher/

#### What Happened Instead

the APPLY FOR JOB BUTTON is on this page
http://www.vedarecruitment.co.uk/job/luton-school-london-16-teacher/

#### WordPress / WP Job Manager Version

1.32.0

#### Browser / OS Version

MAC OSX Mojave

#### Screenshot / Video
screenshot 2019-01-28 at 22 35 39

### PR DESCRIPTION
**Pull request by 0xDELS**
Fixes #1674 

#### Changes proposed in this Pull Request:

* Added a verification to check if the logged user has a role of employer. If it is, the Job Application part is not loaded.

#### Testing instructions:

* Add a new user with the employer role
* Log in with that user
* Navigate through the Job Listings, the Apply Button won't appear. 
* If you use another Role or there isn't a logged in user, the button appears.

#### Proposed changelog entry for your changes:
Hide Apply for Job button for employer

### CODE REVIEW

**Comment by richardmtl** [comment]
Note that in 2061863-zen a different said they tried these changes and it didn't work for them. I have not tried it myself.

**Review by alexsanford — COMMENTED** [review]
I'm not sure about this. Logically, I think it could make sense that the person who posted a job listing should not see an "Apply" button when they visit it. But I'm not certain it always makes sense for an employer to never see the "Apply" button for any job listing in the database. What if the employer also wants to apply for another job on the site? What if a user with a different role posts a job (admins, for example)?

**Comment by jom** [comment]
I agree. We probably should let this be a template customization for now. Thank you for working on the issue, though, @0xDELS .

**Comment by CarlitoDevDreamer** [comment]
Is there a way to only allow logged users to have access to the content of the "Apply for job" button?

**Pull request closed without merging**
