### PR TITLE
Don't allow submit_job_board shortcode in admin

### PR DESCRIPTION
**Pull request by seanvfs**
Don't process shortcode in admin

Fixes #

#### Changes proposed in this Pull Request:

*

#### Testing instructions:

*

### CODE REVIEW

**Comment by jom** [comment]
What is this fixing/preventing? Please provide more information.

**Comment by seanvfs** [comment]
This is fixing an issue where the submit_job_board shortcode executes code in the admin of a page with the shortcode present in the editor.

**Comment by spencerfinnell** [comment]
What is it executing? 

It's standard shortcode implementation so you would be seeing this for everything if something was being executed.

**Comment by seanvfs** [comment]
It was rendering the shortcode output to the admin.  I just tested with a fresh install and couldn't reproduce the problem.  My apologies.  It must have been related to that specific instance.

**Comment by jom** [comment]
@seanvfs Thanks for the PR. If you're able to reproduce and it is caused by something strange that WPJM is doing, feel free to put up another or create an issue.

**Pull request closed without merging**
