### PR TITLE
Update notices

### LINKED ISSUE #2581: Update the designs of notices
We should update the designs of the tracking and setup wizard notices:

Before:

Image

After:

Image

### LINKED ISSUE #2582: Add new upsell banner to Job Listings and Settings page
EDIT:  We just need a new banner on the Job Listings page and WPJM Settings Page to let people know we have paid extensions.

Button will be:
- Job Listings
- Settings Page

**Did you know?**
You can upgrade your job listings with our job manager extensions and add applications, resumes, alerts, and more!

Button:  "View Extensions" takes to the Marketplace page

### PR DESCRIPTION
**Pull request by yscik**
Fixes #2581

Based on #2614 for shared styles

### Changes Proposed in this Pull Request

* Update notice styles
* Bring all notices to use the new notice system
* Use a single 'license required' notice for all add-on license issues
* Limit showing most of the add-ons to main job listing page and settings
* Various copy & action improvements
* Add a few helper methods to get the product icon for an add-on, and a few fixes to the license keys page

### Testing Instructions

* Playground: [Existing site](https://wpjobmanager.com/playground/?core=2023/10/2620-7e20a6fb&url=/wp-admin) | [Fresh site](https://wpjobmanager.com/playground/?core=2023/10/2620-7e20a6fb&site=empty&url=/wp-admin)

* Reset dismissed notices: `wp option delete wp_job_manager_dismissed_notices`
* Reset usage tracking notice:
  * Turn off usage tracking
  * `wp option delete job_manager_usage_tracking_opt_in_hide`
  * `wp option delete job_manager_display_usage_tracking_once`
* Updates, licenses:
  * Add older versions of a few add-ons from https://github.com/Automattic/wpjm-addons/releases
  * In `wp shell`:
  * `include_once JOB_MANAGER_PLUGIN_DIR . '/includes/helper/class-wp-job-manager-helper.php'; WP_Job_Manager_Helper::instance()->check_for_updates([]);`

### Release Notes

* Clean up, update and style admin notices 

### New or Updated Hooks and Templates

*

### Deprecated Code

*

### Screenshot / Video

image

----

| Plugin build for 4cdde5d19813464482a892177016d299c7909923 <a href="#"></a> |
| ------------------------------------------------------------ |
| 📦 [Download plugin zip](https://wpjobmanager.com/wp-content/uploads/2023/10/wp-job-manager-zip-2620-4cdde5d1.zip)                       |
| ▶️ [Open in playground](https://wpjobmanager.com/playground/?core=2023/10/2620-4cdde5d1)             |

### CODE REVIEW

**Comment by fjorgemota** [comment]
Have you based this PR on the PR #2595 too? I see Mikey's commits here. :thinking:

**Comment by yscik** [comment]
Oh yup that branch is also in here :) This should show the actual changes: https://github.com/Automattic/WP-Job-Manager/pull/2620/files/800400f2e4fe2edd693b921bd41543e3dbffaec2..871861d04848b9ebc0ea1af1c0dce755df565974

**Comment by yscik** [comment]
Also quickly added [#2582](https://github.com/Automattic/WP-Job-Manager/issues/2582) in [7b44d63](https://github.com/Automattic/WP-Job-Manager/pull/2620/commits/7b44d63b0f99af13187b68a1b8f3ccd9f554feee) — only showing after the setup wizard notice is already completed.

**Review by mikeyarce — CHANGES_REQUESTED** [review]
Looking great, Peter!

One thing I noticed is that when I dismiss the "Did you know?" Notice, it also dismisses the "Improve your experience" notice.  It's happening because of this hook tha twas added:

```
add_action( 'wp_job_manager_notice_dismissed', [ $this, 'handle_tracking_opt_out' ] );
```
Is that the intended result?  I would think that dismissing one notice should only dismiss that notice itself and not the other ones.

**Comment by yscik** [comment]
> One thing I noticed is that when I dismiss the "Did you know?" Notice, it also dismisses the "Improve your experience" notice. It's happening because of this hook tha twas added:

Good catch, should be fixed by [c572e49](https://github.com/Automattic/WP-Job-Manager/pull/2620/commits/c572e49287563f3ddf12e4cd9303ee079df12653)

**Review by mikeyarce — APPROVED** [review]
Thanks @yscik - looks great! 👍🏽

**Pull request merged**
