### PR TITLE
Types metabox should say Job Types not Job Listings

### PR DESCRIPTION
**Pull request by tripflex**
Job Types metabox title should not say Job Listings, it should say Job Types to match the appropriate taxonomy (this has confused users who are opening support tickets with me about it)

### CODE REVIEW

**Comment by tripflex** [comment]
Related #795

**Review by dbtlr — DISMISSED** [review]
Look good, but please wrap the label in ucwords() to make sure that it maintains a title case like the rest of the meta boxes

```
ucwords( $job_listing_type->label )
```

**Comment by spencerfinnell** [comment]
@dbtlr I think forcing a case defeats the purpose. The idea is to respect whatever the label was set to originally, or filtered to.

**Comment by spencerfinnell** [comment]
I think it would be better to change the cases in the original labels.

**Comment by dbtlr** [comment]
@spencerfinnell I'm requesting this because by default it says 'Post types' which looks awkward compared to the rest of the interface, which has all the meta box titles cased like ucwords().

For me, this is about making sure that the words were correct from the label, not the casing. The casing is a style issue and should remain consistent with the rest of the interface.

**Comment by spencerfinnell** [comment]
What about using the menu label then? 

https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-post-types.php#L143

Which has it applied as well.

**Comment by dbtlr** [comment]
@spencerfinnell I am 100% fine with that solution. :)

**Comment by tripflex** [comment]
Ok no problem, i'll update the PR

**Comment by tripflex** [comment]
Updated the PR to use `menu_name` now

**Comment by dbtlr** [comment]
Thanks for the update. LGTM!

**Pull request merged**
