### PR TITLE
Allow users to specify user password when creating first job listing

### LINKED ISSUE #637: Allow new user to set password
When WPJM is set to create an user account automatically when submitting a job listing, we do not request a password from the new user. Since WordPress no longer e-mails out a pregenerated password, this would require all users to go through the Lost Password flow to determine their password.

The ability for the user to set a password initially would make the process more streamlined.

### PR DESCRIPTION
**Pull request by jom**
Fixes #637 

#### Guiding Principle
Using WordPress' standard behavior of emailing link to set password is best practice. 

#### Changes proposed in this Pull Request:
* Introduces a new setting (`job_manager_use_standard_password_setup_email`) that allows admins to force users to use the standard WordPress flow of getting an email to set their password (default) _or_ be presented with password fields. 
* If the setting to automatically generate usernames is enabled, the `job_manager_use_standard_password_setup_email` setting value will default to `true`. Otherwise, users might not know their username.
* Introduced a few additional filters `wpjm_validate_new_password`, `wpjm_password_rules_hint`, and `wpjm_get_registration_fields` to help support this new functionality. I set the default minimum length to 8. We could put this in a filter or they could just override it in the validation/password rules filters.
* I kept the new naming prefix `wpjm_` for filters/functions, but I propose keeping the `job_manager_` prefix for settings. Way less hassle later on. (#1034)
* Bumped minimum supported WordPress version from 4.1 to 4.3.1 to better support the user creation flow. 4.1 and 4.2 have about 5.1% of all WordPress installs at the time of this PR.

Screencast of the settings: https://cloudup.com/cGa_M-F3THC
Password entry, when enabled: 
screen shot 2017-06-29 at 2 48 23 pm

#### Testing instructions:

* Try the first time job creation flows with all different combinations of user creation settings.

#### Proposed changelog entry for your changes:
* Added the ability for admins to allow users to specify a user password when creating first job listing.

### CODE REVIEW

**Comment by spencerfinnell** [comment]
I think a lot of the logic added to the `account-signin.php` template should be done before and sent to the template. Lots going on there that theme author's don't care about.

Other than I've never been a fan of password verification. It's easy to reset and it's not used anywhere else in WP.

**Comment by jom** [comment]
@spencerfinnell Agreed with first bit. I'll move the field array building somewhere else.

Password verification is easy to remove. I usually have it in when it is obfuscated, but don't have strong opinions about it.

**Comment by annezazu** [comment]
Tested this flow out (both with the setting on and off). Looks great to me!

**Comment by tripflex** [comment]
@jom i've had a few users ask about being able to set password from a password field with my plugin, so i know there are a few out there who want this feature.

We just need to make sure they understand that doing this will completely bypass having the user confirm their email address on registration.

Regarding the password confirmation field, unfortunately I think that is a must ... mainly because a lot of users will end up fat fingering a key or entering it incorrectly and then complaining or getting frustrated because the password doesn't "work" when really they just hit an extra key or didn't enter it correctly.

Besides that, I like the new feature, only thing I could think potential issue wise would be themes that override the template file and need to update it to support this feature

**Comment by jom** [comment]
Thanks, @tripflex. Agreed about email verification. Might be something to add to the help text to the setting.

**Review by dbtlr — APPROVED** [review]
The changes look okay. I'm feeling a bit fazed by all the different naming schemes in use, but obviously, that has nothing to do with this PR. Just looking forward to seeing that fixed/updated soon. :)

**Comment by jom** [comment]
@dbtlr I agree. It bugs me a lot.

**Comment by MrCenty** [comment]
Hey there! I've been waiting like crazy for this! When will it be published in the next update or how can I implement it in WP Job Manager on my site? :)

**Comment by davoraltman** [comment]
@MrCenty The new version together with this enhancement should go out by the end of next week. Cheers :)

**Comment by digitallawyer** [comment]
Thank you!

**Comment by MrCenty** [comment]
Works nicely! But you should include a translation string for the textfield placeholder of the username, password & verify password as there will be errors with the wp job manager field editor plugin because there is no placeholder ! (And it's always nice to be able to edit the placeholders)

**Comment by Maudcr** [comment]
Hi, I am also hoping desperately for this. I bought jobify (including wp job manager) few days ago. How could I have access to this update? Thanks :)

**Comment by jom** [comment]
@Maudcr It is in the most recent release.

**Comment by Maudcr** [comment]
Thanks,

It dosen't seem to be there for me. I bought the theme a few days ago.... Would you have any advice?


Maud Comtois-Rouillard
maud.cr@hotmail.com
(587) 437-3453




________________________________

**Comment by LukeBichard1** [comment]
Hi, will this be included in the resume manager submission form?

**Comment by dipaksaraf** [comment]
Is there any possibilities for adding it in Resume Manager Submission Form?

**Comment by toleabivol** [comment]
How can we add this feature to Resume Manager Submission ?

**Comment by thedigitalcircle** [comment]
Yes, I have also the same problem too. How Can I add this feature with Resume Manager Submission.
This is not yet working with RM.

Shuvashish

**Comment by jom** [comment]
Resume Manager is a separate repository and we are tracking this enhancement request there. We don't have an ETA, but I've added your +1s to that issue.

**Pull request merged**
