### PR TITLE
Use spaces to separate image extensions.

### LINKED ISSUE #1479: Cosmetic change to "Uploaded files need to be..." string.
A user in 1103206-zen reports that the [mention of JPG files](https://github.com/Automattic/WP-Job-Manager/blob/fa9347765e51a9b7cb95554dad841ac7b1256504/wp-job-manager-functions.php#L1291) in the "Uploaded files need to be..." string looks messy:

uploaded_files_need_to_be

 Can we make this look a bit prettier?

### PR DESCRIPTION
**Pull request by oscarssanchez**
Hello,

Could you use this PR which fixes #1479 ?

#### Changes proposed in this Pull Request:

* Add spaces before and after | to separate the output display when an image type is not valid. 

Thanks!

### CODE REVIEW

**Comment by tripflex** [comment]
I don't think this is the right way to fix this.  We should keep the key names without spaces as that is exactly how they are in core WordPress ... really all I think that needs to be done for this is to just do a string replacement on `|` with `, `

**Comment by tripflex** [comment]
Something like this should be used instead:

```php
$allowed_mime_types = array(
    'jpg|jpeg|jpe' => 'image/jpeg',
    'gif'          => 'image/gif',
    'png'          => 'image/png',
);

$allowed_mime_types_csv = implode( ', ', str_replace( '|', ', ', array_keys( $allowed_mime_types ) ) );
```

Produces:

```php
string(24) "jpg, jpeg, jpe, gif, png"
```

**Comment by oscarssanchez** [comment]
Hi @tripflex,

Thanks for your feedback, i see your point, it makes sense that every jpeg extension is separated by a comma as other image formats are separated likewise, hence the cosmetic change looks more ordered.

If it is fine with Auttomatic, i can implement the changes right away.

Thanks again!

**Comment by jom** [comment]
Hi @oscarssanchez! Thanks for this PR. I agree with @tripflex. Even though the `job_manager_get_allowed_mime_types()` function isn't used for that yet, I'd rather update the parsing of the output in the error for `job_manager_upload_file()` to handle `|`.

**Comment by jom** [comment]
Closing for now, but feel free to ask for reopen if you get a chance to refactor.

**Pull request closed without merging**
