### PR TITLE
New user notification action

### PR DESCRIPTION
**Pull request by jamesjonesphoenix**
Allows us to add our own new user notification in place of the default
one. This is by placing an action hook in wp_job_manager_create_account.
The default notification code is placed in it's own function and hooked
in.

I added this because on my site I'd rather use the WooCommerce mailer. I
imagine I wouldn't be the only one who would want a nice looking email
for the notification.
Same issue as this post:
https://wordpress.org/support/topic/new-user-email-notification-1

Now without indent change.

### CODE REVIEW

**Comment by kraftbj** [comment]
Devil's advocate: `wp_new_user_notification` is a pluggable function, so any plugin could declare their own `wp_new_user_notification` and core's wouldn't run. What about defining it that way?

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 12 @ 0:00 (CET):



	Devil's advocate: wp_new_user_notification is a pluggable function,
so any plugin could declare their own wp_new_user_notification and
core's wouldn't run. What about defining it that way? 

	-
 Reply to this email directly or view it on GitHub [1].

Links:
------
[1]
https://github.com/Automattic/WP-Job-Manager/pull/561#issuecomment-155936765


-----------------------------------------------------------

**Comment by jamesjonesphoenix** [comment]
Yeah you're right there's no need for an action really

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 12 @ 6:00 (CET):



	Yeah you're right there's no need for an action really 

	-
 Reply to this email directly or view it on GitHub [1].

Links:
------
[1]
https://github.com/Automattic/WP-Job-Manager/pull/561#issuecomment-155998883


-----------------------------------------------------------

**Pull request merged**
